services:
  # Remove the entire database section - using RDS now!
  # database: <- DELETED - no longer needed

  app:
    build: .
    container_name: itservice_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
      # Updated DATABASE_URL to point to your RDS instance
      - DATABASE_URL=postgresql://postgres:MyPosgresPwd122!@database-1.c7foedg7dnsf.us-east-1.rds.amazonaws.com:5432/itservicedesk?sslmode=require&sslrootcert=/app/rds-ca-cert.pem
      - BASE_URL=https://98.81.235.7
    # Remove depends_on database since we're using external RDS
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: itservice_nginx
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-itservicedesk.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    restart: unless-stopped

# Remove postgres_data volume since we're using RDS
# volumes:
#   postgres_data: <- DELETED - no longer needed
